CREATE TABLE [dbo].[emails]
(
	[Id] INT NOT NULL IDENTITY PRIMARY KEY,
	[Subject] NVARCHAR(256) NULL,
	[Timestamp] DATETIME2(3) NOT NULL,
	[SenderName] NVARCHAR(64) NULL,
	[SenderEmail] NVARCHAR(64) NOT NULL,
	[RecepientName] NVARCHAR(64) NULL,
	[RecepientEmail] NVARCHAR(64) NOT NULL,
	[Content] NVARCHAR(MAX) NULL
)